[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Proxy API routes to Netlify Functions
[[redirects]]
  from = "/api/fetch-url"
  to = "/.netlify/functions/fetch-url"
  status = 200

[[redirects]]
  # Temporary mapping for deprecated schema endpoint; returns 410
  from = "/api/get-schema"
  to = "/.netlify/functions/get-schema"
  status = 200
