[build]
  publish = "public"
  command = "npm ci"

[build.environment]
  NODE_VERSION = "18"
  # Critical environment variables
  BYPASS_AUTH = "true"
  HTTP_DEADLINE_MS = "28000"
  PUBLIC_API_KEY = "public-2024"
  REQUEST_REFERER = "https://news.google.com/"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["src/**"]
  external_node_modules = [
    "natural", "compromise", "jsdom", "cheerio", "axios", "xml2js",
    "undici", "set-cookie-parser", "@mozilla/readability",
    "jszip", "fast-xml-parser"
  ]

[functions."ma-news-scraper"]
  external_node_modules = ["natural", "compromise", "jsdom", "cheerio", "axios", "xml2js"]

# Redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/fetch-url"
  to = "/.netlify/functions/fetch-url"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/ma-news/*"
  to = "/.netlify/functions/ma-news-scraper"
  status = 200
  force = true

# CORS headers for API
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, X-API-Key"
    Access-Control-Max-Age = "86400"

[[headers]]
  for = "/nda/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer"

# Cache static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Static route for Targets page
[[redirects]]
  from = "/targets"
  to   = "/targets/"
  status = 301

# Ensure directory index is served for trailing-slash path
[[redirects]]
  from = "/targets/"
  to   = "/targets/index.html"
  status = 200

[[redirects]]
  from = "/scrape"
  to   = "/scrape/"
  status = 301

[[redirects]]
  from = "/scrape/"
  to   = "/scrape/index.html"
  status = 200

[[redirects]]
  from = "/sports"
  to   = "/sports/"
  status = 301

[[redirects]]
  from = "/sports/"
  to   = "/sports/index.html"
  status = 200

[[redirects]]
  from = "/companies"
  to   = "/companies/"
  status = 301

[[redirects]]
  from = "/companies/"
  to   = "/companies/index.html"
  status = 200

[[redirects]]
  from = "/nda"
  to   = "/nda/"
  status = 301

[[redirects]]
  from = "/nda/"
  to   = "/nda/index.html"
  status = 200
