[build]
  publish = "out"
  functions = "netlify/functions"
  command = "npm run next:build && npm run next:export"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[functions]
  node_bundler = "esbuild"
  included_files = ["prisma/**/*"]

# Proxy API routes to Netlify Functions
[[redirects]]
  from = "/api/fetch-url"
  to = "/.netlify/functions/fetch-url"
  status = 200

[[redirects]]
  # Temporary mapping for deprecated schema endpoint; returns 410
  from = "/api/get-schema"
  to = "/.netlify/functions/get-schema"
  status = 200

# Authentication API Routes
[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200

[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/auth-register"
  status = 200

[[redirects]]
  from = "/api/auth/verify"
  to = "/.netlify/functions/auth-verify"
  status = 200

# Target List Formatter API Routes
[[redirects]]
  from = "/api/uploads/presign"
  to = "/.netlify/functions/uploads-presign"
  status = 200

[[redirects]]
  from = "/api/uploads/commit"
  to = "/.netlify/functions/uploads-commit"
  status = 200

[[redirects]]
  from = "/api/templates"
  to = "/.netlify/functions/templates"
  status = 200

[[redirects]]
  from = "/api/preview"
  to = "/.netlify/functions/preview"
  status = 200

[[redirects]]
  from = "/api/jobs/export"
  to = "/.netlify/functions/jobs-export"
  status = 200

[[redirects]]
  from = "/api/jobs/*"
  to = "/.netlify/functions/jobs-status"
  status = 200

[[redirects]]
  from = "/api/artifacts/*/signed-url"
  to = "/.netlify/functions/artifacts-download"
  status = 200

# New Scraping API Routes for Next.js
[[redirects]]
  from = "/api/scrape/start"
  to = "/.netlify/functions/scrape-start"
  status = 200

[[redirects]]
  from = "/api/scrape/status/*"
  to = "/.netlify/functions/scrape-status"
  status = 200

[[redirects]]
  from = "/api/scrape/cancel/*"
  to = "/.netlify/functions/scrape-cancel"
  status = 200

[[redirects]]
  from = "/api/scrape/download/*"
  to = "/.netlify/functions/scrape-download"
  status = 200

# Catch-all for Next.js pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
