name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  contamination:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run contamination scan
        run: npm run test:contamination
      - name: Git grep contamination patterns
        run: |
          set -e
          PATTERN='(BEGIN PROMPT|END PROMPT|placeholder|lorem ipsum|TODO|FIXME|HACK|BUG|XXX|WIP|@ts-ignore|eslint-disable|ts-nocheck|debugger|console\\.log\\(|\\bprint\\(|sk-[A-Za-z0-9_-]{10,}|ghp_|AKIA|-----BEGIN PRIVATE KEY-----|it\\.skip|describe\\.skip|test\\.skip|\\bxit\\b|\\bxdescribe\\b|\\bpending\\b|<<<<<<<|=======|>>>>>>>|^Resolved$)'
          if git grep -nI -E "$PATTERN" -- ':!package-lock.json' ':!yarn.lock' ':!pnpm-lock.yaml' ':!node_modules/**' ':!dist/**' ':!build/**' ':!coverage/**' ':!outputs/**' ':!sessions/**' \
            src netlify/functions tests tools .github/workflows public/nda; then
            echo 'Contamination pattern detected by git grep.'
            exit 1
          fi
  build:
    runs-on: ubuntu-latest
    needs: contamination
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Test suite
        run: npm test
